# Generated by Django 4.1.9 on 2023-06-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=45)),
                ('vehicle_type', models.CharField(max_length=45)),
                ('checkin_time', models.DateTimeField()),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('parking_amount', models.IntegerField(blank=True, null=True)),
                ('fine_amount', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicle_parking',
                'managed': False,
            },
        ),
    ]
