# Generated by Django 4.1.9 on 2023-07-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicalparkingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_type', models.CharField(blank=True, max_length=45, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'prices',
                'managed': False,
            },
        ),
    ]
