# Generated by Django 4.1.9 on 2023-06-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedetails',
            options={'managed': False},
        ),
    ]
