# Generated by Django 4.1.9 on 2023-06-23 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_authentication', '0002_alter_employeedetails_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeedetails',
            table='employeedetails',
        ),
    ]
