# Generated by Django 4.1.9 on 2023-06-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingDetails',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('no_of_floors', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'building_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FloorDetails',
            fields=[
                ('floor_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor_no', models.CharField(max_length=45)),
                ('no_of_slots', models.IntegerField()),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'floor_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SlotDetails',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_name', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'slot_details',
                'managed': False,
            },
        ),
    ]
